### ISSUE TITLE
rules

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Python-Image-Board#18]
need someone to make a good `rules.html` file relevant to the site ( imageboard ) . This is a very easy thing which can be coded easily by anyone with a bit of experience. Remember the rules page should follow the theme of the main page .

Comment below to be assigned

**Comment by KorryKatti** [comment]
Don't copy paste rules from internet , it needs to be customized to the type of site we have here.

**Comment by lightning-sagar** [comment]
hey can i work on this....

**Comment by KorryKatti** [comment]
> hey can i work on this....

yes please , submit a pr whenever you are done and i will check and merge it

**Comment by lightning-sagar** [comment]
![image](https://github.com/user-attachments/assets/2f81147d-49d4-44f8-b3bd-f755e53cf078)

What do you think about the rules and the theme, particularly from the perspective of the homepage?

**Comment by KorryKatti** [comment]
Looks good , will integrate soon it's midnight here.

Thanks for the PR

**Comment by lightning-sagar** [comment]
Please merge the pr bro

**Comment by lightning-sagar** [comment]
let me know if there is any other task for me 😊

**Comment by KorryKatti** [comment]
> let me know if there is any other task for me 😊

sure , star the repo and stay tuned as more issues will be put up soon.

happy coding
