### ISSUE TITLE
More Comments

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Python-Image-Board#20]
### 🛠️ Issue: Expand Comment System for the Image Board

🚀 **Current State**:  
The image board is currently limited to displaying only **three comments per image**.

🎯 **Goal**:  
- Expand the comment system:
  1. **Preview**: Display the **first three comments** for each image.
  2. **"Read More" Option**: Add a "Read more" button that reveals **all additional comments** for that image.
  
- **Data Storage Requirement**:  
  - **All data** must be stored in **text files** or **JSON files**. **No databases** are allowed.
  - Consider assigning **unique IDs** to each image to help track and manage comments effectively.

📍 **Implementation Scope**:  
- Work on the **/global** page to implement this functionality.
- Ensure that the feature functions smoothly without breaking the existing functionalities.

**📢 Submission Guideline**:
- Once complete, submit a **Pull Request (PR)**.
- If everything works as expected, your PR will be accepted.

💻 **Tip**:  
- Efficiently organize the comment storage, ensuring that additional comments can be retrieved without performance issues.
- Implementing the "Read more" feature in a user-friendly way will improve the overall user experience.

🔗 **Additional Requirements**:
- Comments are managed within **JSON** or **text files**, so make sure the structure supports efficient **reading and appending** of data.

Happy coding! 🚀✨

**Comment by piyushs-05** [comment]
Hey i would like to take the issue , could u assign the issue  to me

**Comment by KorryKatti** [comment]
> Hey i would like to take the issue , could u assign the issue  to me

Please start working on it , will assign to you and will be waiting for your PR

**Comment by piyushs-05** [comment]
Thx , i will update u with pr asap

**Comment by piyushs-05** [comment]
@KorryKatti  check it out i have requested a pr with the changes asked for

**Comment by KorryKatti** [comment]
> @KorryKatti check it out i have requested a pr with the changes asked for

will check soon , thanks for the PR
