### ISSUE TITLE
Improve Header UI across website

### ISSUE THREAD

**Issue by ayushmankoley** [KorryKatti/Python-Image-Board#21]
Add proper button UI to header for the Website, also sticking to the website theme

**Comment by ayushmankoley** [comment]
@KorryKatti can you assign this to me

**Comment by KorryKatti** [comment]
> Add proper button UI to header for the Website, also sticking to the website theme

could you show what exactly would it look like after the changes . i will assign you to after it

**Comment by ayushmankoley** [comment]
![image](https://github.com/user-attachments/assets/e1603a10-255f-4d7c-bf4a-8792b224ea2e)
I was planning like this, staying true to the b/w theme, home button shows hover color change

**Comment by KorryKatti** [comment]
> ![image](https://private-user-images.githubusercontent.com/80102808/373602673-e1603a10-255f-4d7c-bf4a-8792b224ea2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMzc3NjIsIm5iZiI6MTcyODAzNzQ2MiwicGF0aCI6Ii84MDEwMjgwOC8zNzM2MDI2NzMtZTE2MDNhMTAtMjU1Zi00ZDdjLWJmNGEtODc5MmIyMjRlYTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDEwMjQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMGU4MGFiOTY0NWM3MzYzMTVhMjQ5MDY3NTNiZjc3MDQ0NmM5Y2MxMzliNWU3NTg4N2MxMmE2NDUyMTQ0OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XrsQdLQjOVZg8x9Me9vw6BxgfyTrT6O2XdS3Vy-TFIk) I was planning like this, staying true to the b/w theme, home button shows hover color change

it does look good but i want it to stay as the text links it is so i will be closing this issue, if you have any other ui improvements then do let me know

**Comment by ayushmankoley** [comment]
@KorryKatti okay no problem, I was wondering if you are looking for some UI changes in places like Topic/Links section
I was thinking a design like 
![image](https://github.com/user-attachments/assets/23a67b8f-8283-4ce0-b654-a85262069bc0)
lmk

**Comment by KorryKatti** [comment]
> @KorryKatti okay no problem, I was wondering if you are looking for some UI changes in places like Topic/Links section I was thinking a design like ![image](https://private-user-images.githubusercontent.com/80102808/373607910-23a67b8f-8283-4ce0-b654-a85262069bc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMzg4MTMsIm5iZiI6MTcyODAzODUxMywicGF0aCI6Ii84MDEwMjgwOC8zNzM2MDc5MTAtMjNhNjdiOGYtODI4My00Y2UwLWI2NTQtYTg1MjYyMDY5YmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDEwNDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYTMzY2YyNzM5YWRmYjFjZDUzMDM0OWFhMTk0YzNiZWE0ODMxYTZmNWE4MmFlZWY2MDYzYmIyNDdkYjA0MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kqz__P7JzM6eK3FGA_w0mmz3bZgtAtPTmK36hbwvl3w) lmk

re-opened the issue , would love to have this , also while you are at it you could look at #22 too. Let me know your final decision

**Comment by ayushmankoley** [comment]
@KorryKatti I will send the pr for the mentioned UI update, I'm looking further into the mobile adaptivity
also assign this issue to me and add the relevant tags

**Comment by ayushmankoley** [comment]
also what is your contact info? the twitter link in the thunder page is broken

**Comment by KorryKatti** [comment]
> also what is your contact info? the twitter link in the thunder page is broken

discord works or its dunkelkron on twitter
