### ISSUE TITLE
Mobile Friendly

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Python-Image-Board#22]
### 📱 Issue: Improve Mobile Responsiveness

🚧 **Current State**:  
The website does not render well on mobile devices, leading to a suboptimal user experience.

🎯 **Task**:  
Your objective is to modify the HTML files to ensure the website is **fully responsive** and fits nicely on mobile screens.

🌟 **Contribution**:  
- This issue counts towards **Hacktoberfest**!  
- Make your contribution and help enhance the user experience for mobile users.

📢 **Guidelines**:  
- Ensure all elements are responsive and accessible on various mobile devices.
- Test your changes on different screen sizes to ensure compatibility.

🔗 **Additional Note**:  
- Please submit your **Pull Requests (PR)** once you have made your changes. I will be looking forward to reviewing your contributions! 

⭐️ **Don't forget** to star the repo and share it with your friends participating in the fest!

Happy coding and good luck! 🎉✨

**Comment by KorryKatti** [comment]
fixed with the ui updates PR #23

**Comment by KorryKatti** [comment]
still if anyone can improve it even better i will reopen this

**Comment by varunsehgal02** [comment]
hey i would like to take this issue and improve the ui for mobile

**Comment by varunsehgal02** [comment]
https://github.com/user-attachments/assets/def2ee17-0ee1-4e44-9671-992e2d305686

here is the video of Thunder page as asked for , let me know if any changes are required

**Comment by varunsehgal02** [comment]
https://github.com/user-attachments/assets/8335bbf8-a08f-4445-90fa-4398fe4a5059

Here is the video of Thunder page as asked for , let me know if any changes are required

**Comment by KorryKatti** [comment]
looks good , please submit a pr
