### ISSUE TITLE
UI improvement and Image slider

### ISSUE THREAD

**Issue by Nitish36** [KorryKatti/Python-Image-Board#3]
Hi i am planning to improve the UI of this website and also to create a option kind off to upload images and to make a database type to store whatever the images are uploaded. Please make this hacktoberfest accepted

**Comment by KorryKatti** [comment]
we store the image uploaded in a json already , don't see the need for a separate database ?

**Comment by Nitish36** [comment]
Okay. For UI changes can I try?

**Comment by KorryKatti** [comment]
yes , if you see the issues i need a new global.html page under the templates folder, you can work on that , and if possible you should also implement a separate image data json for it to keep it apart from thunder.html


I will accept only a new webpage too if it meets the basic criteria of keeping the functionality of the site. 
`global.html` is what you need to make inside the templates folder

for example on basic structure check this out https://korrykatti.pythonanywhere.com/thunder

Will be waiting for your pr

**Comment by Nitish36** [comment]
Got it will start working on that. Thank you

**Comment by KorryKatti** [comment]
its done #14
