### ISSUE TITLE
Add Image Deletion Feature Using Uploaders' Password

### ISSUE THREAD

**Issue by Boobeshkumar56** [KorryKatti/Python-Image-Board#4]
I propose to add a feature that allows uploaders to delete their images using their upload password. Currently, there is an
 option for uploaders to delete their images. By implementing a password box and a delete button, users can securely remove their images from the site. Additionally, I recommend enhancing the user interface for a better user experience.
Please assign this issue under Hacktoberfest.

**Comment by KorryKatti** [comment]
is this about thunder.html ? the images are supposed to be deleted by admin only since their is no authentication to check if the user deleting is same as the user uploading the image.

**Comment by Boobeshkumar56** [comment]
I want to add a new feature that lets users upload images with a password. This way, users can easily delete their images later if they want to. Admins will also have the option to delete images when necessary. This change will give users more control over their content, making the platform feel more reliable and decentralized.

**Comment by KorryKatti** [comment]
> I want to add a new feature that lets users upload images with a password. This way, users can easily delete their images later if they want to. Admins will also have the option to delete images when necessary. This change will give users more control over their content, making the platform feel more reliable and decentralized.

sounds good , i will be assigning this issue to you. Just remember to test it before implementing as i won't re-open a closed PR. 

also will you be willing to wait for someone to make `global.html` or will you like to start working on `thunder.html` ?

**Comment by Boobeshkumar56** [comment]
i would like to start work on thunder.html

**Comment by KorryKatti** [comment]
alright great , please ensure that no error is made since thunder.html is a more important file.

Have fun coding

**Comment by Boobeshkumar56** [comment]
tThank you for assigning me the issue! I appreciate the guidance on testing before submitting the pull request. I will ensure everything is thoroughly tested

**Comment by KorryKatti** [comment]
done with #29
