### ISSUE TITLE
need an imageboard

### ISSUE THREAD

**Issue by KorryKatti** [KorryKatti/Python-Image-Board#6]
`global.html` now works , please make an image board for it , first pr which does it will be accepted,

Remember the data for global imageboard should be stored in a different json file than the thunder one

**Comment by Abhinavexists** [comment]
I will do it.

**Comment by KorryKatti** [comment]
alright assigning you , be sure to test your code before pushing

**Comment by Abhinavexists** [comment]
I will take care of that.

**Comment by Shouryan-Bharote** [comment]
ok i am working on /global 
i have created 
1.form UI for uploading Image 
2.functions to upload image 
3.created a new json file named "global_images.json"

can u assign me this task

**Comment by KorryKatti** [comment]
assigned , be sure the code works fine and you are good to go

**Comment by Shouryan-Bharote** [comment]
I have made a PR Please check @KorryKatti

**Comment by KorryKatti** [comment]
i will check in a while , bit busy rn

**Comment by Abhinavexists** [comment]
@KorryKatti i have also made a pr can you check

**Comment by KorryKatti** [comment]
> @KorryKatti i have also made a pr can you check

checking

**Comment by KorryKatti** [comment]
@Shouryan-Bharote : your imageboard redirects to index page and has no password option
@Abhinavks1405 : your imageboard doesn't render the latest update popup and displays it as a text in html instead , also the images are very small , they should be large and one below each other like in /thunder




Whoever fixes their issue first will have their PR merged, I am closing the already open PR's for now , make sure to submit a new PR

**Comment by Shouryan-Bharote** [comment]
I have checked the thunder page's password field
and have failed to recognize its purpose or what the password is for exactly

since we need the same password field in the Global Page 
Please Clear my Doubt

**Comment by KorryKatti** [comment]
> I have checked the thunder page's password field and have failed to recognize its purpose or what the password is for exactly
> 
> since we need the same password field in the Global Page Please Clear my Doubt

the password field is used by the admin to delete images which are nsfw or potentially bad , so the person who knows the password can delete the image , and by delete the image it removes the entry of the image in the json file. 

hope i made it clear

**Comment by Shouryan-Bharote** [comment]
> > I have checked the thunder page's password field and have failed to recognize its purpose or what the password is for exactly
> > since we need the same password field in the Global Page Please Clear my Doubt
> 
> the password field is used by the admin to delete images which are nsfw or potentially bad , so the person who knows the password can delete the image , and by delete the image it removes the entry of the image in the json file.
> 
> hope i made it clear

Alright I got it so I will make these changes

1.Create The password Field
2.Create The Delete Button
3.RenderTemplate(Global) after Uploading Image or Commenting Image

**Comment by KorryKatti** [comment]
> > > I have checked the thunder page's password field and have failed to recognize its purpose or what the password is for exactly
> > > since we need the same password field in the Global Page Please Clear my Doubt
> > 
> > 
> > the password field is used by the admin to delete images which are nsfw or potentially bad , so the person who knows the password can delete the image , and by delete the image it removes the entry of the image in the json file.
> > hope i made it clear
> 
> Alright I got it so I will make these changes
> 
> 1.Create The password Field 2.Create The Delete Button 3.RenderTemplate(Global) after Uploading Image or Commenting Image

sounds good to me

**Comment by Abhinavexists** [comment]
@KorryKatti made the changes , please review

**Comment by KorryKatti** [comment]
This is now done in #12

**Comment by KorryKatti** [comment]
Issue is still open since comments is not working and showing invalid image index and also on submitting a comment its redirecting to index


so well @Shouryan-Bharote you can still improve the code

**Comment by KorryKatti** [comment]
![image](https://github.com/user-attachments/assets/1ceb7438-5841-4c38-bbee-c0340e76a972)
this is what it is looking like right now

**Comment by Shouryan-Bharote** [comment]
Thank You @KorryKatti for tagging me again 
i will continue working on the code

**Comment by KorryKatti** [comment]
great

**Comment by Shouryan-Bharote** [comment]
@KorryKatti 
completed the requested changes

**Comment by KorryKatti** [comment]
> @KorryKatti completed the requested changes

testing now

**Comment by KorryKatti** [comment]
Thanks for the work , this issue closes now
