### ISSUE TITLE
Project management using Poetry for scalability

### ISSUE THREAD

**Issue by hitblast** [KorryKatti/Python-Image-Board#9]
## Why?

Most Python projects, small or big, need a centralized solution for managing things properly. But stuff end up scattering since all of the different packages have their own way of managing things. I think it'd be great for this project if over time it could be centralized using [Poetry](https://python-poetry.org/), a not-necessarily-new but advanced tool.

## How?

The first step would be to initialize Poetry within the project. Later on, we could integrate the structure for a Python package within this project to make a whole range of tasks possible (e.g. creating a separate command for managing the image board), both at the user side and the developer's side. It can also be used to manage development dependencies too, which also brings a whole different set of issues for other contributors to work on.

**Comment by hitblast** [comment]
Update: #8 integrates the initialization part.

**Comment by KorryKatti** [comment]
> Update: #8 integrates the initialization part.

is there anything more left to it ? i would like to close this issue

**Comment by hitblast** [comment]
> > Update: #8 integrates the initialization part.
> 
> is there anything more left to it ? i would like to close this issue

If you want, you can. Won't necessarily need it for the coming contributions.

**Comment by KorryKatti** [comment]
alright thanks for your contribution
